# Generated by Django 5.0.8 on 2026-03-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetellFunctionCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function_name', models.CharField(max_length=128)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('payload_json', models.JSONField(default=dict)),
                ('response_json', models.JSONField(blank=True, default=dict, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
